import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import picJsItems from './docs/pic-js/typedoc-sidebar.cjs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  apiSidebar: [...picJsItems],
};

export default sidebars;
